[package]
name = "Hyrule-Builder"
version = "0.1.0"
authors = ["Caleb Smith <caleb@myrvmail.com>"]
edition = "2018"

[lib]
name = "hyrule_builder"
crate-type = ["cdylib"]

[dependencies]
anyhow = "1.0"
botw-utils = "0.3.1"
chrono = "0.4"
colored = "2.0.0"
crc = "^1.0.0"
glob = "0.3"
indexmap = { version = "1.6", features = ["rayon"] }
msyt = { git = "https://github.com/NiceneNerd/msyt", tag = "v1.2.1" }
rayon = "1.5"
roead = { path = "../roead" }
# roead = { git = "https://github.com/NiceneNerd/roead.git", rev = "7fde63473d13f432360d48ec1aca106bad0e3969" } 
relative-path = "1.3.2"
sarc-rs = "0.1.3"
serde_yaml = "0.8.17"
path_macro = "1.0"
path-slash = "0.1.3"

[dev-dependencies]
rand = "0.8.3"

[dependencies.pyo3]
version = "0.13.2"
features = ["extension-module"]

# [profile.release]
# lto = "fat"
