[package]
name = "Hyrule-Builder"
version = "0.1.0"
authors = ["Caleb Smith <caleb@myrvmail.com>"]
edition = "2018"

[lib]
name = "hyrule_builder"
crate-type = ["cdylib"]

[dependencies]
aamp = "0.1.1"
byml = "0.1.2"
# byml = { version = "0.1.1", path = "../byml-rust" }
botw-utils = "0.2.0"
chrono = "0.4"
crc = "^1.0.0"
glob = "0.3.0"
indexmap = { version = "1.6.0", features = ["rayon"] }
rayon = "1.5.0"
sarc = "1.1.2"
path_macro = "1.0.0"
path-slash = "0.1.3"
yaz0 = { git = "https://github.com/NiceneNerd/yaz0-rs", version = "0.1.2" }

[dependencies.pyo3]
version = "0.12.3"
features = ["extension-module"]

[profile.release]
lto = true
