[package]
name = "Hyrule-Builder"
version = "0.1.0"
authors = ["Caleb Smith <caleb@myrvmail.com>"]
edition = "2018"

[lib]
name = "hyrule_builder"
crate-type = ["cdylib"]

[dependencies]
aamp = "0.1.5"
anyhow = "1.0"
byml = "0.1.4"
botw-utils = "0.3.1"
chrono = "0.4"
crc = "^1.0.0"
glob = "0.3"
indexmap = { version = "1.6.0", features = ["rayon"] }
mimalloc = { version = "0.1.17", default-features = false }
msyt = { git = "https://github.com/NiceneNerd/msyt", tag = "v1.2.1" }
once_cell = "1.7.2"
owning_ref = "0.4.1"
rayon = "1.5"
sarc = "1.1.3"
sarc-rs = "0.1.3"
serde_yaml = "0.8.17"
path_macro = "1.0"
path-slash = "0.1.3"
yaz0 = "0.3.0" #{ git = "https://github.com/NiceneNerd/yaz0-rs" }

[dev-dependencies]

[dependencies.pyo3]
version = "0.13.2"
features = ["extension-module"]

[profile.release]
lto = "fat"
